ERROR 2020-10-01 17:07:11,827 log 7177 139837171353344 Internal Server Error: /my_account/pools/add_existing/
Traceback (most recent call last):
  File "/home/cloudcopasi/cloud-copasi-new/ccEnv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/cloudcopasi/cloud-copasi-new/ccEnv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/ccEnv/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/ccEnv/lib64/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/ccEnv/lib64/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/cloud_copasi/web_interface/pools/pool_views.py", line 713, in dispatch
    return super(BoscoPoolAddView, self).dispatch(*args, **kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/ccEnv/lib64/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/ccEnv/lib64/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/cloud_copasi/web_interface/views.py", line 117, in dispatch
    return super(RestrictedFormView, self).dispatch(request, *args,**kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/ccEnv/lib64/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/ccEnv/lib64/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/cloud_copasi/web_interface/views.py", line 89, in dispatch
    return super(RestrictedView, self).dispatch(request, *args, **kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/cloud_copasi/web_interface/views.py", line 53, in dispatch
    return super(DefaultView, self).dispatch(request, *args, **kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/ccEnv/lib64/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/cloud_copasi/web_interface/views.py", line 145, in post
    return self.form_valid(**kwargs)
  File "/home/cloudcopasi/cloud-copasi-new/cloud_copasi/web_interface/pools/pool_views.py", line 747, in form_valid
    output = process.communicate()
AttributeError: 'CompletedProcess' object has no attribute 'communicate'
